# Generated by Django 3.1.2 on 2020-10-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('categories', models.CharField(choices=[('election', 'Election 2020'), ('US', 'US News'), ('world', 'Worlds News'), ('entertainment', 'Entertainment'), ('tech', 'Technology')], default=None, max_length=15)),
            ],
        ),
    ]
