# Generated by Django 3.1.2 on 2020-10-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201015_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
